In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
netflix_dataset = pd.read_csv('/content/drive/MyDrive/Netflix Dataset/Copy of combined_data_1.txt.zip', header =None , names=['Cust_Id' , 'Ratings'] , usecols=[0,1])

In [ ]:
netflix_dataset

          Cust_Id  Ratings
0              1:      NaN
1         1488844      3.0
2          822109      5.0
3          885013      4.0
4           30878      4.0
...           ...      ...
24058258  2591364      2.0
24058259  1791000      2.0
24058260   512536      5.0
24058261   988963      3.0
24058262  1704416      3.0

[24058263 rows x 2 columns]

In [ ]:
movie_count = netflix_dataset.isnull().sum()
movie_count = movie_count['Ratings']
movie_count

np.int64(4499)

In [ ]:
total_count = netflix_dataset['Cust_Id'].nunique()

In [ ]:
customer_count = total_count-movie_count
customer_count

np.int64(470758)

In [ ]:
rating_count= netflix_dataset['Cust_Id'].count()- movie_count

In [ ]:
rating_count

np.int64(24053764)

In [ ]:
stars = netflix_dataset['Ratings'].value_counts()

In [ ]:
stars

Ratings
4.0    8085741
3.0    6904181
5.0    5506583
2.0    2439073
1.0    1118186
Name: count, dtype: int64

In [ ]:
movie_id = None
movie_np = []

for customer in netflix_dataset['Cust_Id']:
  if ":" in customer:
    movie_id = int(customer.replace(":"  , ""))


  movie_np.append(movie_id)

In [ ]:
movie_np

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [ ]:
netflix_dataset['Movie_Id'] = movie_np

In [ ]:
netflix_dataset.dropna(inplace=True)

In [ ]:
netflix_dataset

          Cust_Id  Ratings  Movie_Id
1         1488844      3.0         1
2          822109      5.0         1
3          885013      4.0         1
4           30878      4.0         1
5          823519      3.0         1
...           ...      ...       ...
24058258  2591364      2.0      4499
24058259  1791000      2.0      4499
24058260   512536      5.0      4499
24058261   988963      3.0      4499
24058262  1704416      3.0      4499

[24053764 rows x 3 columns]

In [ ]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   Cust_Id   object
 1   Ratings   float64
 2   Movie_Id  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 734.1+ MB

In [ ]:
netflix_dataset['Cust_Id']=netflix_dataset['Cust_Id'].astype(int)

In [ ]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   Cust_Id   int64
 1   Ratings   float64
 2   Movie_Id  int64
dtypes: float64(1), int64(2)
memory usage: 734.1 MB

In [ ]:
movie_re_count = netflix_dataset['Movie_Id'].value_counts()

In [ ]:
#movie_re_count= netflix_dataset.groupby('Ratings')['Ratings'].agg('count')

In [ ]:
movie_re_count

Movie_Id
1905    193941
2152    162597
3860    160454
4432    156183
571     154832
         ...
4294        44
915         43
3656        42
4338        39
4362        36
Name: count, Length: 4499, dtype: int64

In [ ]:
bench_mark = round(movie_re_count.quantile(0.6) , 0)  #48.0 --> 48

In [ ]:
bench_mark

np.float64(908.0)

In [ ]:
drop_movie_index = movie_re_count[movie_re_count<bench_mark].index

In [ ]:
drop_movie_index

Index([1598, 1647, 1733, 4099, 1616, 1446,  263,  160, 4259,  322,
       ...
       1858, 4035, 3693, 2805,  820, 4294,  915, 3656, 4338, 4362],
      dtype='int64', name='Movie_Id', length=2699)

In [ ]:
cust_rew_count = netflix_dataset['Cust_Id'].value_counts()

In [ ]:
cust_rew_count

Cust_Id
305344     4467
387418     4422
2439493    4195
1664010    4019
2118461    3769
           ...
739382        1
1504246       1
1244849       1
1558754       1
258446        1
Name: count, Length: 470758, dtype: int64

In [ ]:
bench_mark_cus = round(cust_rew_count.quantile(0.6),0)

In [ ]:
bench_mark_cus

np.float64(36.0)

In [ ]:
drop_cust_index = cust_rew_count[cust_rew_count<bench_mark_cus].index

In [ ]:
drop_cust_index

Index([1804808, 2619850, 1023928, 1475023, 2569169, 1961632, 2548215, 2390820,
       1691756, 2485501,
       ...
         11326,  116898,   68286, 1847608, 1685763,  739382, 1504246, 1244849,
       1558754,  258446],
      dtype='int64', name='Cust_Id', length=282042)

In [ ]:
drop_movie_index , drop_cust_index

(Index([1598, 1647, 1733, 4099, 1616, 1446,  263,  160, 4259,  322,
        ...
        1858, 4035, 3693, 2805,  820, 4294,  915, 3656, 4338, 4362],
       dtype='int64', name='Movie_Id', length=2699),
 Index([1804808, 2619850, 1023928, 1475023, 2569169, 1961632, 2548215, 2390820,
        1691756, 2485501,
        ...
          11326,  116898,   68286, 1847608, 1685763,  739382, 1504246, 1244849,
        1558754,  258446],
       dtype='int64', name='Cust_Id', length=282042))

In [ ]:
netflix_dataset = netflix_dataset[~netflix_dataset['Movie_Id'].isin(drop_movie_index)]
netflix_dataset = netflix_dataset[~netflix_dataset['Cust_Id'].isin(drop_cust_index)]

In [ ]:
netflix_dataset

          Cust_Id  Ratings  Movie_Id
696        712664      5.0         3
697       1331154      4.0         3
698       2632461      3.0         3
699         44937      5.0         3
700        656399      4.0         3
...           ...      ...       ...
24056842  1055714      5.0      4496
24056843  2643029      4.0      4496
24056844   267802      4.0      4496
24056845  1559566      3.0      4496
24056846   293198      3.0      4496

[19695836 rows x 3 columns]

In [ ]:
movie_title = pd.read_csv('/content/drive/MyDrive/Netflix Dataset/Copy of movie_titles.csv', encoding ='ISO-8859-1', header =None , names=['Movie_Id' , 'Year' ,'Name'] , usecols=[0,1,2])

In [ ]:
movie_title

       Movie_Id    Year                                               Name
0             1  2003.0                                    Dinosaur Planet
1             2  2004.0                         Isle of Man TT 2004 Review
2             3  1997.0                                          Character
3             4  1994.0                       Paula Abdul's Get Up & Dance
4             5  2004.0                           The Rise and Fall of ECW
...         ...     ...                                                ...
17765     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766     17767  2004.0                  Fidel Castro: American Experience
17767     17768  2000.0                                              Epoch
17768     17769  2003.0                                        The Company
17769     17770  2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [ ]:
#!pip install numpy==1.23.5

In [ ]:
from surprise import SVD ,  Reader , Dataset
from surprise.model_selection import cross_validate

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-4237784044.py", line 1, in <cell line: 0>
    from surprise import SVD ,  Reader , Dataset
  File "/usr/local/lib/python3.11/dist-packages/surprise/__init__.py", line 6, in <module>
    from .prediction_algorithms import (
  File "/usr/local/lib/python3.11/dist-packages/surprise/prediction_algorithms/__init__.py", line 23, in <module>
    from .algo_base import AlgoBase
  File "/usr/local/lib/python3.11/dist-packages/surprise/prediction_algorithms/algo_base.py", line 8, in <module>
    from .. import similarities as sims

ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).

In [ ]:
reader = Reader()

In [ ]:
data = Dataset.load_from_df(netflix_dataset[['Movie_Id' , 'Cust_Id' , 'Ratings']][:100000], reader)

In [ ]:
data

In [ ]:
model = SVD()

In [ ]:
cross_validate(model , data , measures=['RMSE'] , cv=3)

In [ ]:
user_rating = netflix_dataset[netflix_dataset['Cust_Id'] == 1331154]

In [ ]:
user_rating

In [ ]:
user_1331154 = movie_title.copy()
user_1331154

In [ ]:
user_1331154 = user_1331154[~user_1331154['Movie_Id'].isin(drop_movie_index)]

In [ ]:
user_1331154

In [ ]:
user_1331154['Estimated']=user_1331154['Movie_Id'].apply(lambda x:model.predict(1331154,x).est)

In [ ]:
user_1331154

In [ ]:
user_1331154.sort_values('Estimated' , ascending=False)

In [ ]:
user_1331154.head()

In [ ]:
popular_genres = df['genre'].value_counts().reset_index()
popular_genres.columns = ['Genre']

In [ ]:
#!pip show numpy surprise

In [ ]:
#!pip install numpy==1.23.5